### ISSUE TITLE
Problem with map . 

### ISSUE THREAD

**Issue by Daviesss** [hikashi/multi-robot-rrt-exploration-noetic#13] opened 2024-02-29 12:22 UTC
Hello , i have been able to configure all the packages and Node to be able to use turtlebot3 "burger" . But there is a problem . All works when exploring with the robots, but for some reason which i don't know why . After some while . This happens . The description below. I appreciate any advice to solve this.

![Screenshot from 2024-02-29 13-16-37](https://github.com/hikashi/multi-robot-rrt-exploration-noetic/assets/97457075/f250f4fc-bccb-4017-afb2-d797f2f411a8)

**Comment by Daviesss** [comment] 2024-02-29 12:32
> Hello , i have been able to configure all the packages and Node to be able to use turtlebot3 "burger" . But there is a problem . All works when exploring with the robots, but for some reason which i don't know why . After some while . This happens . The description below. I appreciate any advice to solve this.
> 
> ![Screenshot from 2024-02-29 13-16-37](https://private-user-images.githubusercontent.com/97457075/308920841-f250f4fc-bccb-4017-afb2-d797f2f411a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTAyMjUsIm5iZiI6MTcwOTIwOTkyNSwicGF0aCI6Ii85NzQ1NzA3NS8zMDg5MjA4NDEtZjI1MGY0ZmMtYmNjYi00MDE3LWFmYjItZDc5N2YyZjQxMWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDEyMzIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNDUwYWRhYWNlNDg3Y2FiYzcxMGU3MDhkMzdhNjg3YmU0MzQ3MmYwMzcwYzE0MWE2ZDk0Y2Y4YzBlMjdhODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uMfVW4mlJMK5fucc3sb45G4n2JVyGiv7SYp-6TpFGrk)

![Screenshot from 2024-02-29 13-16-37](https://github.com/hikashi/multi-robot-rrt-exploration-noetic/assets/97457075/f2c3899c-a16e-4712-9da0-071b6991f31f)

**Comment by hikashi** [comment] 2024-03-01 04:58
For your information, RRT is a boundary-based exploration, which only happens inside a bounding box. 
The yellow box from your screenshot indicates the bounding box for the exploration, where it would not expand beyond it. You should work on the map-merging tools by supplying the optimal settings to eliminate the problem you are facing. 

From what I can tell, there are a few potential problems that will cause an issue for exploration:
- initial map size too small
- map merging can't seem to merge the map or do you hide it in Rviz?
- the exploration is based on two maps (robot local map and global merged map)
- is the global cost map for the robots working as intended?

I believe if you go through the original author's paper, you should have a rough idea of what stack is running and the underlying working mechanism.

**Comment by Daviesss** [comment] 2024-03-01 07:52
> For your information, RRT is a boundary-based exploration, which only happens inside a bounding box. 
> The yellow box from your screenshot indicates the bounding box for the exploration, where it would not expand beyond it. You should work on the map-merging tools by supplying the optimal settings to eliminate the problem you are facing. 
> 
> From what I can tell, there are a few potential problems that will cause an issue for exploration:
> - initial map size too small
> - map merging can't seem to merge the map or do you hide it in Rviz?
> - the exploration is based on two maps (robot local map and global merged map)
> - is the global cost map for the robots working as intended?
> 
> I believe if you go through the original author's paper, you should have a rough idea of what stack is running and the underlying working mechanism.  

  
  Thanks for your reply. I relaunched the node, and everything is working fine so far. I will let you know if any errors arise, and I'll also review these steps and inform you. Also, can a pull request be sent for "Burger"? I would appreciate your feedback. Thank you in advance.

Regards.

**Comment by Daviesss** [comment] 2024-03-06 09:41
> For your information, RRT is a boundary-based exploration, which only happens inside a bounding box. The yellow box from your screenshot indicates the bounding box for the exploration, where it would not expand beyond it. You should work on the map-merging tools by supplying the optimal settings to eliminate the problem you are facing.
> 
> From what I can tell, there are a few potential problems that will cause an issue for exploration:
> 
>     * initial map size too small
> 
>     * map merging can't seem to merge the map or do you hide it in Rviz?
> 
>     * the exploration is based on two maps (robot local map and global merged map)
> 
>     * is the global cost map for the robots working as intended?
> 
> 
> I believe if you go through the original author's paper, you should have a rough idea of what stack is running and the underlying working mechanism.

Good Morning,

  Thanks for last time . I still have the same problem , even after following these steps. How can i solve this issue ?

**Comment by hikashi** [comment] 2024-03-07 04:38
Sorry to hear about that. I think most probably related to your mapping stack problems.
As for the merge map not functioning properly, you may refer to [multi-robot merge map](https://github.com/hrnr/m-explore) for more queries on how merge-map works.

**Comment by Daviesss** [comment] 2024-03-07 07:27
Do you think the issue may be from the map merge ? Or ? Reason why I'm asking is the robots explore, but after some while the map shift like you can see in the description  above . What do you think may be the problem?

**Comment by hikashi** [comment] 2024-03-12 04:37
most probably is your merge map configuration having trouble. 
Since you have changed to "burger", the sensor height and localization configuration could be different.
You will have to reconfigure those yourself to fix the map shifting as map-merge only leverage opencv to merge CV. You will need to have certain common features in order for the merge map to function properly.

**Comment by Daviesss** [comment] 2024-03-12 07:44
> most probably is your merge map configuration having trouble. 
> Since you have changed to "burger", the sensor height and localization configuration could be different.
> You will have to reconfigure those yourself to fix the map shifting as map-merge only leverage opencv to merge CV. You will need to have certain common features in order for the merge map to function properly. 

Is the  opencv Merge cv added to the repo ? Looks like there isn't any open cv functionalities.  Probably  the robot's aren't noticing the common features. That's why the merge keeps failing..

**Comment by hikashi** [comment] 2024-03-12 09:06
It's built-in inside the merge map folder (Please read the paper and previous author's research work). 
It's common to have a weird merging effect and thus merge incorrectly (problems for others to solve).

As mentioned in the read file, I only did the conversion from ROS Kinetic to ROS Noetic. 
The problems that originally came with the original files will persist even after I did the conversion. 

You can choose to fix the problem if you find one. I would be glad to commit to the changes if so.

**Closed as completed** 2024-03-18 04:29 UTC
